version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: chat_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: chat_app
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    depends_on:
      db:
        condition: service_started

volumes:
  postgres_data: